name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/school-management:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/school-management:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/school-management:buildcache,mode=max

      - name: Deploy to production
        run: |
          echo "Add your deployment commands here"
          # Example: Deploy to a cloud service or server
          # You'll need to add specific deployment steps based on your hosting environment